import { v4 as uuidv4 } from "uuid";

export const initialState = {
  fetchRateStatus: "idle",
  selectedCurrency: "USD",
  currencies: {
    base: "USD",
    rates: { ILS: 3.3 },
  },
  stores:["amazon", "ebay", "ali-baba"],
  error: "",
  items: [
    {
      id: uuidv4(),
      name: "AA",
      onlineStore: "amazon",
      price: 20.2,
      deliveryDate: new Date("August 19, 1975").valueOf(),
      isRecived: false,
    },
    {
      id: uuidv4(),
      name: "BB",
      onlineStore: "ali-baba",
      price: 11.2,
      deliveryDate: new Date("July 1, 2020").valueOf(),
      isRecived: false,
    },
    {
      id: uuidv4(),
      name: "BB",
      onlineStore: "ali-baba",
      price: 11.2,
      deliveryDate: new Date("July 1, 2020").valueOf(),
      isRecived: false,
    },
    {
      id: uuidv4(),
      name: "BB",
      onlineStore: "ali-baba",
      price: 11.2,
      deliveryDate: new Date("July 1, 2020").valueOf(),
      isRecived: false,
    },
    {
      id: uuidv4(),
      name: "BB",
      onlineStore: "ali-baba",
      price: 11.2,
      deliveryDate: new Date("July 1, 2020").valueOf(),
      isRecived: false,
    },
    {
      id: uuidv4(),
      name: "BB",
      onlineStore: "ali-baba",
      price: 11.2,
      deliveryDate: new Date("July 1, 2020").valueOf(),
      isRecived: false,
    },
    {
      id: uuidv4(),
      name: "BB",
      onlineStore: "ali-baba",
      price: 11.2,
      deliveryDate: new Date("July 1, 2020").valueOf(),
      isRecived: false,
    },
    {
      id: uuidv4(),
      name: "BB",
      onlineStore: "ali-baba",
      price: 11.2,
      deliveryDate: new Date("July 1, 2020").valueOf(),
      isRecived: false,
    },
  ],
};
